@url_dev=http://localhost:3001/v1/api/

### create new 
POST {{url_dev}}product
Content-Type: application/json
x-api-key: 4de98ec2ceb93a69ed72126ab8b6e5938ca3311cab5f2d0530194a4ae6c04d97ca2d12c78a01e7e8e1c92752e8c7f76eb2244427734426b976f0987f1610803a
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzcyNmQ5Zjk5YzFlMTExNGE0MDBiMGIiLCJlbWFpbCI6InNob3AxQGdtYWlsLmNvbSIsImlhdCI6MTczNzAxODgxMywiZXhwIjoxNzM3MTkxNjEzfQ.M6YwmM-MB0vEfY-t89rj7zwiR7lxD96BKsET9NVxE9Q
client-id: 67726d9f99c1e1114a400b0b

{
    "product_name" :"product 2",
    "product_thumb" :"product_thumb",
    "product_description" :"product_description",
    "product_price" :15,
    "product_quantity" :30,
    "product_type" :"clothing",
    "product_attributes": {
        "brand": "Brand A",
        "size": "L",
        "material": "Denim"
    }
}

